@startuml
'https://plantuml.com/activity-diagram-beta

start
:Display image;
:Draw rectangles by coordinates;
:Display question if the coordinates are correct;


while (if the coordinates are correct) is (False)
    :Ask user about new coordinates;
    :User provides new coordinates;
    :Display image with new rectangles;
endwhile (True)
stop

'Output:
'Change enum's value for user's changed ones
'If enum can not be changed, assign values to new variable

@enduml
