@startuml
'https://plantuml.com/activity-diagram-beta

start
:Display image;
:Draw rectangles by coordinates;
:Display question if the coordinates are correct;
if (if the coordinates are correct) then (true)
    stop
else (false)
    :Ask user about new coordinates;
    :User provides new coordinates;
endif
stop
@enduml
